version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node API service
  api:
    build: .     # 👈 Add this line to build from local Dockerfile
    image: nodeapp
    container_name: api_container
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}
