# Generated by Django 5.2.4 on 2025-08-07 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.IntegerField(
                    primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('st', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(
                    primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dealership', models.IntegerField()),
                ('review', models.TextField()),
                ('purchase', models.BooleanField()),
                ('purchase_date', models.CharField(max_length=20)),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_year', models.IntegerField()),
                ('sentiment', models.CharField(
                    blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(
                    choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'),
                             ('WAGON', 'Wagon'),
                             ('HATCHBACK', 'Hatchback'),
                             ('COUPE', 'Coupe'),
                             ('CONVERTIBLE', 'Convertible')],
                    default='SEDAN', max_length=20)),
                ('year', models.IntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(2015),
                        django.core.validators.MaxValueValidator(2023)])),
                ('car_make', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='djangoapp.carmake')),
            ],
        ),
    ]
