# Generated by Django 5.2.4 on 2025-08-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
    ]
